require:
  - rubocop-rails
  - rubocop-rspec
  - rubocop-performance

AllCops:
  Exclude:
    - 'vendor/**/*'

Style/AsciiComments:
  Enabled: false

Style/Documentation:
  Exclude:
    - "db/**/*.rb"
    - "config/**/*.rb"

Style/MixinUsage:
  Exclude:
    - "bin/**/*"

Layout/LineLength:
  Max: 160
  Exclude:
    - "spec/**/*.rb"

Metrics/AbcSize:
  Max: 30
  Exclude:
    - "db/**/*.rb"

Metrics/BlockLength:
  Exclude:
    - "spec/**/*.rb"
    - "db/**/*.rb"

Metrics/MethodLength:
  Exclude:
    - "db/**/*.rb"

RSpec/AnyInstance:
  Enabled:
    false

RSpec/ContextWording:
  Enabled:
    false

RSpec/ExampleLength:
  Enabled:
    false

RSpec/MultipleExpectations:
  Enabled:
    false

RSpec/NestedGroups:
  Enabled:
    false